#!/usr/bin/env python3
"""Utility used by GitHub Actions to replace template placeholders."""

from __future__ import annotations

import os
import pathlib
import subprocess
import sys
from typing import List, Tuple

EnvReplacements = List[Tuple[str, str]]


def _require_env(key: str) -> str:
    try:
        return os.environ[key]
    except KeyError as exc:  # pragma: no cover - defensive guard
        raise SystemExit(f"Missing required environment variable: {key}") from exc


def build_replacements() -> EnvReplacements:
    package_name = _require_env("PACKAGE_NAME")
    package_name_dart = _require_env("PACKAGE_NAME_DART")
    project_name = _require_env("PROJECT_NAME")
    supabase_url = _require_env("SUPABASE_URL")
    supabase_anon_key = _require_env("SUPABASE_ANON_KEY")
    target_owner = _require_env("TARGET_OWNER")
    target_repo = _require_env("TARGET_REPO")

    return [
        ("Vigilo ", project_name),
        ("Vigilo ", project_name),
        ("Generated by OneWeekApp", "Generated by OneWeekApp"),
        ("com.oneweekapp.vigilo ", package_name),
        ("com.oneweekapp.vigilo ", package_name),
        ("com.oneweekapp.vigilo ", package_name),
        ("vigilo ", package_name_dart),
        ("vigilo ", package_name_dart),
        ("Vigilo ", project_name),
        ("https://txylavmjhzcsqajcfbqy.supabase.co ", supabase_url),
        ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eWxhdm1qaHpjc3FhamNmYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNzY2MjgsImV4cCI6MjA3OTg1MjYyOH0.R4DqcYaVfJ6RxsWOwtiQ5Q7wmCiFkNhWRU6YK0FX21c ", supabase_anon_key),
        ("sabatino81 ", target_owner),
    ]


def replace_in_repo(root: pathlib.Path, replacements: EnvReplacements) -> int:
    changed_files = 0
    output = subprocess.check_output(["git", "ls-files", "-z"], cwd=root)
    for rel_path in output.decode().split("\0"):
        if not rel_path:
            continue
        path = root / rel_path
        try:
            original = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, IsADirectoryError):
            continue

        updated = original
        for old, new in replacements:
            updated = updated.replace(old, new)

        if updated != original:
            path.write_text(updated, encoding="utf-8")
            changed_files += 1

    return changed_files


def main() -> None:
    repo_root = pathlib.Path(os.environ.get("WORKING_DIR", ".")).resolve()
    replacements = build_replacements()
    changed = replace_in_repo(repo_root, replacements)
    print(f"Placeholder replacement complete. Files touched: {changed}")


if __name__ == "__main__":
    sys.exit(main())
